name: API Update
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    name: Node ${{ matrix.node }} - Build
    outputs:
      version: ${{ steps.bump.outputs.newTag }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - name: Fetch API
        run: npm run fetch
      - name: Check cache
        id: cache
        uses: actions/cache@v3
        with:
          path: firefly-iii-spec.yaml
          key: ${{ hashFiles('firefly-iii-spec.yaml') }}
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run ci
      - name: Commit
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update API"
      - name: Bump
        if: steps.cache.outputs.cache-hit != 'true'
        id: bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: patch
          target-branch: main
      - name: Archive built files
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    name: Publish to NPM
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Download built files
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Publish NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built files
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            dist/**/*
          name: firefly-api ${{ needs.build.outputs.version }}
          tag_name: ${{ needs.build.outputs.version }}
